name: pkg-config
version:
  source: "url:https://pkgconfig.freedesktop.org/releases/"
  exclude_patterns: "(alpha|beta|rc|dev|preview|pre|snapshot|nightly|test|unstable|canary|next|edge|weekly|daily)"
  extract_pattern: 'pkg-config-([0-9]+\.[0-9]+(?:\.[0-9]+)?)\.tar'

build_type: gnu_autotools
description: "pkg-config for managing compile/link flags"

download:
  download_url: "https://pkgconfig.freedesktop.org/releases/pkg-config-{version}.tar.gz"
  mirror: "https://pkgconfig.freedesktop.org/releases/pkg-config-{version}.tar.gz"
  platforms:
    darwin-x86_64:
    darwin-arm64:
    linux-amd64:
    linux-arm64:

security:
  verify_signature: false
  # gpg_keys_url: ""  # Add URL to project KEYS file for auto-import
  scan_vulnerabilities: true

configure:
  flags: ""

build:
  timeout_minutes: 30

dependencies: []
