name: actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "recipes/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "recipes/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    name: GitHub Actions Workflow Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Run actionlint
        uses: reviewdog/action-actionlint@7eeec1dd160c2301eb28e1568721837d084558ad # v1
        with:
          actionlint_flags: -color
